"""empty message

Revision ID: 4c7d0a7a99aa
Revises: 20406dcabce5
Create Date: 2020-08-09 20:54:39.639355

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c7d0a7a99aa'
down_revision = '20406dcabce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'comments',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_index('name', table_name='images')
    op.drop_index('s3_path', table_name='images')
    op.drop_column('images', 'deleted_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('deleted_at', mysql.DATETIME(), nullable=True))
    op.create_index('s3_path', 'images', ['s3_path'], unique=True)
    op.create_index('name', 'images', ['name'], unique=True)
    op.alter_column('images', 'comments',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
